experiment:
  name: prueba_4
  save_dir: experiment
  seeds: [0]

model:

  cnn:
    embedding_dim: 512

  adapter:
    factor: 2
    dropout: 0.5
  
  transformer_encoder:
    num_heads: 2
    num_layers: 2
    mlp_size: 256
  mlp:
    hidden_units_mlp: [256,128]
  dropout: 0.5

train:
  num_classes: 5
  epochs: 30
  warmup_epochs: 5
  lr: 0.001
  weight_decay: 0.005

  optimizer: adamw
  scheduler:
    name: warmup-cosine-decay
    reduceLrOnPlateau: null
    stepLr: null
    cosineAnnealingLr: null

data:
  dataset:
    root: datasets/resized_warehouse_actions
    selector:
      strategy: uniform
      candidate_frames: null
      selected_frames: 15
    resize_size: 110
    crop_size: 96
  
  dataloader:
    batch_size: 64
    num_workers: 2

