# Model
# 1: MViT
# 2: S3D 
# 3: Video ResNet
# 4: Video Swin Transformer
# 5: ViViT

experiment:
  name: r3d_prueba_4
  save_dir: experiment
  model: 3
  seeds: [0,1,2,3,4]
  phase: 4

train:
  num_classes: 5

data:
  dataset:
    root: datasets/dataset_split_r3d_tensor
    selector:
      strategy: uniform
      candidate_frames: null
      selected_frames: 16
  
  dataloader:
    batch_size: 12
    num_workers: 0

