# Model
# 1: MViT
# 2: S3D
# 3: Video ResNet
# 4: Video Swin Transformer
# 5: ViViT

experiment:
  name: prueba_1_video_swin
  save_dir: experiment
  model: 4
  seeds: [0]

train:
  num_classes: 5
  epochs: 10
  warmup_epochs: 4

data:
  dataset:
    root: datasets/resized_warehouse_actions
    selector:
      strategy: uniform
      candidate_frames: null
      selected_frames: 16
  
  dataloader:
    batch_size: 4
    num_workers: 0

