# Model
# 1: MViT
# 2: S3D
# 3: Video ResNet
# 4: Video Swin Transformer
# 5: ViViT

experiment:
  name: prueba_4
  save_dir: experiment
  model: 1
  seeds: [0]

train:
  num_classes: 5
  epochs: 10
  warmup_epochs: 4

data:
  dataset:
    root: videos/mini_dataset
    selector:
      strategy: uniform
      candidate_frames: null
      selected_frames: 15
  
  dataloader:
    batch_size: 2
    num_workers: 1

